### ISSUE TITLE
Any recommended samples to use for modeling/training?

### ISSUE THREAD

**Issue by 38github** [GuitarML/PedalNetRT#17]
I would like to try to setup modeling of a few pedals, compressors, etc. Is there any good sound files to use to model/train these? I guess the audio should have sections of transients, loss of transients, harmonic sounds, clean sounds with no harminics, different amplitudes, full frequency range, limited frequency range, etc?

Thanks in advance!

**Comment by 38github** [comment]
I did not know what to do so I threw together an input file with different attributes (drums, bass, tones, noise, etc) and sent it through a Really Nice Leveling Amp (7239) and a Cal Martin DC Drive.

Do you think these files are usable? They are all 44100Hz / 32bit FP / mono.

Source (audio sample): [https://cdn.sndup.net/9qbf/the_sampling_file.mp3?token=cMFoOt6IhIXElg5fCFavDtix504OBbRGkO8qV_XrWCM&token_path=%2F9qbf%2F&expires=1607515509](url)
DC Drive (audio sample): [https://cdn.sndup.net/4y64/dcdrive+%234.mp3?token=eQcTByxQOqF5mn9VBx99Ze7CGi7x3W18wTEcottT7mk&token_path=%2F4y64%2F&expires=1607515545](url)
RNLA 7239 (audio sample): [https://cdn.sndup.net/9kn4/rnla7230+%237.mp3?token=gTKaOOmxGxNiLBEZLzB47PXHh57_3Q5cAgOBCjfAYBw&token_path=%2F9kn4%2F&expires=1607515574](url)

DC Drive files: [https://easyupload.io/3d3f6y](url)
RNLA7239 files: https://easyupload.io/0ticcq

**Comment by GuitarML** [comment]
@38github you are exploring new territory so I'm not really sure what to tell you, if it's able to run training then the format is good (mono, 44.1k, float32). I have not tried any instruments other than electric guitar, and very limited testing on compressors. I'd love to hear your results if you want to share the .h5 models. When I get some time I can test out your samples but you're probably able to get to it before I can. At this point it's all about experimentation and figuring out what the network is capable of learning. Since the hardware I have on hand is limited, I'm really relying on the open source community to try new things, so thanks for doing just that!

**Comment by 38github** [comment]
Thank you for your reply. I am right now trying (very hard) to install everything in Tumbleweed so that I can train the models. We'll see how it goes and I will report back to you.

**Comment by 38github** [comment]
For eight hours I have been trying to get train.py to work after I prepared_data.py successfully (I think). I have tried CUDA versions of pytorch and I have tried onlycpu but I get the following (this is with onlycpu):

```
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    main(args)
  File "train.py", line 40, in main
    trainer = pl.Trainer(max_epochs=args.max_epochs, gpus=args.gpus, row_log_interval=100)
  File "C:\Users\hello\miniconda3\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'row_log_interval'
```

I have the latest Anaconda3/Miniconda3 (tried both) and have installed pytorch and pytorch-lightning among other things that I have tried.

**Comment by 38github** [comment]
I am trying out your GuitarLSTM right now and that is interesting and works! I will play around with that and send you a .h5 file when I have produced something that is usable. Right now I only tried five epochs to hear how it sounds.

I realy look forward to the upcoming plugin to be able to play the GuitarLSTM models.

**Comment by 38github** [comment]
I think I give up. I have now done a lot of training using many different parameters and achieved down to 0.0013 loss and still it does not sound good. One thing for certain that is not possible, or at least not when I try, is to make it model compressors. There is no "ADSR sound" or pumping.

What am I missing?

**Comment by GuitarML** [comment]
@38github can you copy and paste your command line input for some of your runs?

**Comment by 38github** [comment]
Sorry, I posted in the wrong project, it should have been in GuitarLSTM. I will post it over there. Sorry for the inconvenience.

**Comment by 38github** [comment]
I tried the command lines that are on the first page.

**Comment by GuitarML** [comment]
What you're getting seems like a very similar error to this:

https://github.com/PyTorchLightning/pytorch-lightning/issues/991

What version of pytorch-lightning are you using?

**Comment by 38github** [comment]
That did unfortunately not help. That is a shame because I would really like to try out this. I even followed the YouTube guide and still it does not work.

**Comment by basarane** [comment]
@38github I received the same error. I don't know the reason for the error. I just removed `row_log_interval=100` from `pl.Trainer` lines and it worked.

**Comment by mishushakov** [comment]
@basarane @38github please try my fork

git clone https://github.com/mishushakov/PedalNetRT -b refactor

**Comment by mishushakov** [comment]
@GuitarML please see lightning change log
https://pytorch-lightning.readthedocs.io/en/stable/CHANGELOG.html#id38

**Comment by GuitarML** [comment]
That will do it, thanks @mishushakov. I'll make a quick fix in the master branch by removing that flag.

**Comment by mishushakov** [comment]
@GuitarML replace it with `log_every_n_steps`

**Comment by GuitarML** [comment]
Done, thanks again, if there are any further issues let me know.  I'll review the pytorch-lightning changelogs in more detail just in case.

**Comment by 38github** [comment]
Thank you everyone. I will try it out as soon as possible.
