### ISSUE TITLE
Test.py and Predict.py render sound file half speed

### ISSUE THREAD

**Issue by stephanepericat** [GuitarML/PedalNetRT#19]
Hi @GuitarML ,

does the sound samples provided to prepare_data.py need to be in 32 bit ? I tested with sound samples in 16 bit, and the result was that when i ran the test.py and predict.py, the generated sound files were slowed down half speed :(

Is there a way to fix the model after the fact ? or do i need to re-run the training ?

Also, I think it would be nice to mention the required file format for the input samples in the documentation :)

Regards,
Stephane

**Comment by stephanepericat** [comment]
should have read the docs... my bad.

**Comment by GuitarML** [comment]
@stephanepericat no problem! Glad you got it working.
